openapi: 3.0.0
info:
  title: PostgreSQL Database YAML Spec Schema
  version: 1.0.0
components:
  schemas:
    DatabaseSpec:
      type: object
      properties:
        schemas:
          type: array
          items:
            $ref: '#/components/schemas/SchemaSpec'
        tables:
          type: array
          items:
            $ref: '#/components/schemas/TableSpec'
        foreign_keys:
          type: array
          items:
            $ref: '#/components/schemas/ForeignKeySpec'
      required: ['schemas', 'tables']
      
    SchemaSpec:
      type: object
      properties:
        name:
          type: string
        owner:
          type: string
        grants:
          type: array
          items:
            $ref: '#/components/schemas/GrantSpec'
      required: ['name']

    GrantSpec:
      type: object
      properties:
        role:
          type: string
        privileges:
          type: array
          items:
            type: string
        with_grant_option:
          type: boolean

    TableSpec:
      type: object
      properties:
        schema:
          type: string
          description: Schema name for the table
        name:
          type: string
        owner:
          type: string
        columns:
          type: array
          items:
            $ref: '#/components/schemas/ColumnSpec'
        grants:
          type: array
          items:
            $ref: '#/components/schemas/GrantSpec'
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/ConstraintSpec'
      required: ['name', 'columns']

    ColumnSpec:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        not_null:
          type: boolean
        default:
          oneOf:
            - type: string
            - type: number
            - type: boolean
        unique:
          type: boolean

      required: ['name', 'type']

    ConstraintSpec:
      type: object
      properties:
        type:
          type: string
          enum: ['PRIMARY KEY', 'FOREIGN KEY', 'CHECK', 'UNIQUE']
        columns:
          type: array
          items:
            type: string
        expression:
          type: string

    ForeignKeySpec:
      type: object
      properties:
        table:
          type: string
        columns:
          type: array
          items:
            type: string
        references:
          type: object
          properties:
            schema:
              type: string
            table:
              type: string
            columns:
              type: array
              items:
                type: string
          required: ['table', 'columns']
      required: ['table', 'columns', 'references']
